// front/src/components/common/header.vue
<style>

</style>

<template>
    <!--
    <div class="demo-container" mdl-shadow="2">
        <mdl-layout mdl-layout-fixed-header>
            <mdl-layout-header>
                <mdl-layout-header-row>
                    <mdl-layout-title>SpeedJob</mdl-layout-title>
                    <mdl-layout-spacer></mdl-layout-spacer>
                    &lt;!&ndash; Navigation. We hide it in small screens. &ndash;&gt;
                    <nav class="mdl-navigation mdl-layout&#45;&#45;large-screen-only">
                        <a class="mdl-navigation__link" >Link</a>
                        <a class="mdl-navigation__link" >Link</a>
                        <a class="mdl-navigation__link" >Link</a>
                    </nav>
                </mdl-layout-header-row>
            </mdl-layout-header>
            <mdl-layout-drawer>
                <mdl-layout-title>Title</mdl-layout-title>
                <nav class="mdl-navigation">
                    <a class="mdl-navigation__link" >Link</a>
                    <a class="mdl-navigation__link" >Link</a>
                    <a class="mdl-navigation__link" >Link</a>
                </nav>
            </mdl-layout-drawer>
            <mdl-layout-content>
                &lt;!&ndash; Your content goes here &ndash;&gt;
                <router-outlet></router-outlet>
            </mdl-layout-content>
        </mdl-layout>
    </div>-->
    <p>Header</p>
</template>

<script>
    import Vue from 'vue'

    export default {

    }
</script>

// front/src/app/common/header/header.component.ts
import { Component, OnInit, Injectable } from '@angular/core';
import { Router } from '@angular/router';

import { AccountService } from '../../services/account.service';

@Component({
    selector: 'app-header',
    templateUrl: './header.component.html',
    styleUrls: ['header.component.scss']
})

@Injectable()
export class HeaderComponent implements OnInit {

    constructor(private accountService: AccountService,
                private router: Router) {}

    ngOnInit() {

    }

    logOut() {
        this.accountService.logOut();
    }

}

<div class="demo-container" mdl-shadow="2">
    <mdl-layout mdl-layout-fixed-header>
        <mdl-layout-header>
            <mdl-layout-header-row>
                <mdl-layout-title>SpeedJob</mdl-layout-title>
                <mdl-layout-spacer></mdl-layout-spacer>
                <!-- Navigation. We hide it in small screens. -->
                <nav class="mdl-navigation mdl-layout--large-screen-only">
                    <a class="mdl-navigation__link" >Link</a>
                    <a class="mdl-navigation__link" >Link</a>
                    <a class="mdl-navigation__link" >Link</a>
                </nav>
            </mdl-layout-header-row>
        </mdl-layout-header>
        <mdl-layout-drawer>
            <mdl-layout-title>Title</mdl-layout-title>
            <nav class="mdl-navigation">
                <a class="mdl-navigation__link" >Link</a>
                <a class="mdl-navigation__link" >Link</a>
                <a class="mdl-navigation__link" >Link</a>
            </nav>
        </mdl-layout-drawer>
        <mdl-layout-content>
            <!-- Your content goes here -->
            <router-outlet></router-outlet>
        </mdl-layout-content>
    </mdl-layout>
</div>
