// front/src/app/sign-in/sign-in.component.ts
import {Component, Injectable, OnInit} from '@angular/core';
import { Response } from '@angular/http';
import { Router } from '@angular/router';

// Service
import { AccountService } from "../services/account.service";

@Component({
    selector: 'sign-in',
    templateUrl: 'sign-in.component.html',
    styleUrls: ['./sign-in.component.scss']
})

@Injectable()
export class SignInComponent implements OnInit {
    login: string;
    password: string;
    isLoading: boolean = false;

    constructor (private accountService: AccountService,
                 private router: Router) {}

    ngOnInit() {}

    logIn() {
        this.isLoading = true;

        this.accountService.logIn(this.login, this.password)
         .subscribe((res: Response) => {
             // Account has been validated
             if ((res.json()).success == true) {
                 localStorage.setItem('speedjob', JSON.stringify(res.json()));
                 this.router.navigate(['/home']);

             } else {
                 console.log(res.json());
             }
         });
    }
}
<div class="container">
    <div class="row">

        <div class="col-sx-12">
            <h1 class="logo text-align">SpeedJob</h1>

            <p>Plateforme d'embauche entre les entreprises et l'école du numérique IMIE</p>
        </div>

        <div class="col-xs-12 col-sm-offset-2 col-sm-4">
            <h4>Déjà membre sectaire ?</h4>

            <form>
                <mdl-textfield class="col-xs-12"
                               type="text"
                               label="Votre identifiant..."
                               [(ngModel)]="login"
                               name="login"
                               floating-label></mdl-textfield>

                <mdl-textfield class="col-xs-12"
                               type="password"
                               label="Mot de passe"
                               [(ngModel)]="password"
                               name="password"
                               floating-label></mdl-textfield>

                <button class="col-xs-12"
                        mdl-button
                        mdl-ripple
                        mdl-colored="primary"
                        (click)="logIn()"
                        type="submit">
                    Se connecter
                </button>
            </form>
        </div>

        <div class="col-xs-12 col-sm-4">
                <h4>Vous ne tenez plus en place et désirez de suite enroler un de nos valeureux guerriers du numérique ?!</h4>

                <h3>N'hésitez pas un instant de plus et inscrivez-vous ici :</h3>

            <button mdl-button
                    mdl-ripple
                    mdl-colored="primary"
                    (click)="logIn()"
                    type="submit">
                S'inscrire
            </button>
        </div>

    </div>
</div>

// front/src/components/views/sign-in/sign-in.vue
<style>

</style>

<template>
    <div class="container">
        <div class="row">

            <div class="col-sx-12">
                <h1 class="logo text-align">SpeedJob</h1>

                <p>Plateforme d'embauche entre les entreprises et l'école du numérique IMIE</p>
            </div>

            <div class="col-xs-12 col-sm-offset-2 col-sm-4">
                <h4>Déjà membre sectaire ?</h4>

                <form>
                    <mdl-textfield class="col-xs-12"
                                   type="text"
                                   label="Votre identifiant..."
                                   v-model="login"
                                   name="login"
                                   floating-label></mdl-textfield>

                    <mdl-textfield class="col-xs-12"
                                   type="password"
                                   label="Mot de passe"
                                   v-model="password"
                                   name="password"
                                   floating-label></mdl-textfield>

                    <button class="col-xs-12"
                            mdl-button
                            mdl-ripple
                            mdl-colored="primary"
                            @click="logIn()"
                            type="submit">
                        Se connecter
                    </button>
                </form>
            </div>

            <div class="col-xs-12 col-sm-4">
                <h4>Vous ne tenez plus en place et désirez de suite enroler un de nos valeureux guerriers du numérique ?!</h4>

                <h3>N'hésitez pas un instant de plus et inscrivez-vous ici :</h3>

                <button mdl-button
                        mdl-ripple
                        mdl-colored="primary"
                        @click="logIn()"
                        type="submit">
                    S'inscrire
                </button>
            </div>

        </div>
    </div>
</template>

<script>
    import Vue from 'vue'

    export default {

    }
</script>
